name: Python package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies with uv
        run: |
          uv lock
          uv sync --frozen --extra dev --extra publishing
      - name: Download en_ner_bc5cdr_md
        run: |
          pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.0/en_ner_bc5cdr_md-0.5.0.tar.gz
      - name: Run unit tests
        run: uv run python -m pytest -v
      - name: Verify that we can build the package
        run: uv run python -m build
  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies with uv
        run: |
          uv lock
          uv sync --frozen --extra dev
      - name: Check style against standards using ruff
        run: |
          uv run ruff check
          uv run ruff format --check
