name: documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies with uv
        run: |
          uv sync --extra dev --extra publishing
      - name: Install pandoc using apt
        run: sudo apt install pandoc
      - name: Build documentation
        run: uv run make -C docs coverage doctest html
